nodeLinker: node-modules
packageExtensions:
  astro@*:
    peerDependencies:
      typescript: '^5.0.0'
  recma-jsx@*:
    peerDependencies:
      acorn: '^6.0.0 || ^7.0.0 || ^8.0.0'
  '@mdx-js/mdx@*':
    peerDependencies:
      acorn: '^6.0.0 || ^7.0.0 || ^8.0.0'
