name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm


      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test --run
